version: '3.4'

services:
  whoami:
    image: nginx
    environment:
      VIRTUAL_HOST: cloud.impleri.com
    ports:
      - "80"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: infra_default